/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.github.pwczar.cblgame;

import java.awt.*;
import javax.swing.*;

/**
 * Main application class.
 */
public class App extends JPanel {
    JFrame frame;
    private Scene scene;
    private Thread sceneThread;

    /**
     * Initialize App and create a window.
     */
    App() {
        frame = new JFrame("CBL Game");
        frame.add(this);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 800);
        // make the window appear at the center of the screen
        frame.setLocationRelativeTo(null);

        frame.setVisible(true);
    }

    /**
     * Change current scene.
     * @param scene scene
     */
    void setScene(Scene scene) {
        if (this.sceneThread != null) {
            this.sceneThread.interrupt();
        }

        this.scene = scene;
        this.sceneThread = new Thread(this.scene);
        this.sceneThread.start();
    }

    /**
     * Redraw the game window.
     */
    public void paintComponent(Graphics g) {
        /*
        g.clearRect(0, 0, this.getWidth(), this.getHeight());
        for (Entity e : drawables) {
            e.draw(g);
        }
        */
        if (scene != null) {
            scene.draw(g);
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.setScene(new Game(app));
    }
}
